# 📚 What We Collected & Preprocessed

This notebook documents all the **reference datasets** that ship with `oracc-parser`.
These were curated, merged, and pre-saved so you never have to re-download or reprocess them.

| Dataset | Source                              | How it's stored |
|---|-------------------------------------|---|
| **ORACC project catalogue** | Manually curated from ORACC + live API | Bundled CSV |
| **Provenance (cities → Pleiades)** | ORACC raw fields + Pleiades API     | Bundled CSV |
| **Historical periods → year ranges** | Scholarly literature                | Bundled CSV |
| **Cuneiform sign readings** | ORACC sign lists (8,900+ entries)   | Bundled CSV |
| **POS tag meanings** | ORACC documentation                 | Bundled CSV |
| **Language codes** | ORACC documentation                 | Bundled CSV |

All datasets load instantly from inside the installed package — no internet needed.
To explore downloading and parsing tablet texts, see **Notebook 01** (Quickstart).

## 🎯 Goals of this notebook

1. **Understand what was collected** — overview of all bundled reference datasets
2. **Browse the project catalogue** — 221 ORACC projects with metadata
3. **Explore provenance data** — raw find-sport strings → cities → Pleiades coordinates
4. **Explore period mappings** — historical period names → year ranges
5. **Explore the sign list** — 8,900+ cuneiform sign readings
6. **Explore POS tags & language codes** — ORACC annotation conventions

In [15]:
from oracc_parser import reference_data

# All reference data is accessed through reference_data.*
# These load from bundled CSVs inside the package — no download needed.

## 1. ORACC Project Catalogue

We pre-saved metadata for **all known ORACC projects** — including project names,
languages, URLs, and whether the project has parseable text content.

> **Note:** This is a *static snapshot* bundled with the package.
> For a live count from ORACC's servers, use `reference_data.get_live_project_list()` (Notebook 01).

In [16]:
projects = reference_data.get_projects_metadata()
print(f"🌍 {len(projects)} ORACC projects in the bundled catalogue")
display(projects.head(10))

🌍 221 ORACC projects in the bundled catalogue

,Project,Link,Project_Name,Languages,Is_Umbrella_Project,Is_Text_Folder_Empty,Last_Check
0,adsd: adsd/Astronomical Diaries and Related Texts,http://oracc.museum.upenn.edu/adsd,adsd,Akkadian,yes,yes,14/05/2025
1,adsd/adart1: adsd/Astronomical Diaries and Rel...,http://oracc.museum.upenn.edu/adsd/adart1,adsd/adart1,Akkadian,no,no,14/05/2025
2,adsd/adart2: adsd/Astronomical Diaries and Rel...,http://oracc.museum.upenn.edu/adsd/adart2,adsd/adart2,Akkadian,no,no,14/05/2025
3,adsd/adart3: adsd/Astronomical Diaries and Rel...,http://oracc.museum.upenn.edu/adsd/adart3,adsd/adart3,Akkadian,no,no,14/05/2025
4,adsd/adart5: adsd/Astronomical Diaries and Rel...,http://oracc.museum.upenn.edu/adsd/adart5,adsd/adart5,Akkadian,no,no,14/05/2025
5,adsd/adart6: adsd/Astronomical Diaries and Rel...,http://oracc.museum.upenn.edu/adsd/adart6,adsd/adart6,Akkadian,no,no,14/05/2025
6,AEMW: Akkadian in the Eastern Mediterranean World,https://oracc.museum.upenn.edu/aemw,aemw,"Akkadian, Ugaritic",yes,no,14/05/2025
7,aemw/idrimi: Statue of Idrimi,http://oracc.museum.upenn.edu/aemw/alalakh/idrimi,aemw/alalakh/idrimi,Akkadian,no,no,14/05/2025
8,aemw/amarna: The Amarna Letters,http://oracc.museum.upenn.edu/aemw/amarna,aemw/amarna,Akkadian,no,no,14/05/2025
9,aemw/ugarit — AEMW Ugarit Corpus,https://oracc.museum.upenn.edu/aemw/ugarit/corpus,aemw/ugarit,"Akkadian, Ugaritic",no,no,14/05/2025

In [17]:
# Search for projects by keyword (searches all columns)
SEARCH = "saa"

# fillna('') handles missing values safely before joining
mask = projects.apply(
    lambda r: SEARCH.lower() in ' '.join(r.fillna('').astype(str)).lower(),
    axis=1,
)
matches = projects[mask]
print(f"Found {len(matches)} projects matching '{SEARCH}':")
display(matches)

Found 29 projects matching 'saa':

,Project,Link,Project_Name,Languages,Is_Umbrella_Project,Is_Text_Folder_Empty,Last_Check
38,ATAE: Private Neo-Assyrian Archives in the Vor...,https://oracc.museum.upenn.edu/atae/saab0509/,atae/saab0509/,Akkadian,no,no,14/05/2025
39,ATAE: Neo-Assyrian Archival Texts from Nineveh,https://oracc.museum.upenn.edu/atae/nineveh/,atae/saao,Akkadian,no,yes,14/05/2025
40,ATAE: Neo-Assyrian Archival Texts from Assur,https://oracc.museum.upenn.edu/atae/assur/,atae/saaoassur,Akkadian,no,yes,14/05/2025
41,ATAE: Neo-Assyrian Archival Texts from Kalhu,https://oracc.museum.upenn.edu/atae/kalhu/,atae/saaokalhu,Akkadian,no,yes,14/05/2025
162,SAAo: State Archives of Assyria Online,http://oracc.museum.upenn.edu/saao,saao,Akkadian,yes,yes,14/05/2025
163,Assyrian Empire Builders,http://oracc.museum.upenn.edu/saao/aebp,saao/aebp,NaN,no,yes,14/05/2025
164,Knowledge and Power,http://oracc.museum.upenn.edu/saao/knpp,saao/knpp,NaN,no,yes,14/05/2025
165,SAAo/SAA01: The Correspondence of Sargon II Pa...,http://oracc.museum.upenn.edu/saao/saa01,saao/saa01,Akkadian,no,no,14/05/2025
166,SAAo/SAA02: Neo-Assyrian Treaties and Loyalty ...,http://oracc.museum.upenn.edu/saao/saa02,saao/saa02,Akkadian,no,no,14/05/2025
167,SAAo/SAA03: Court Poetry and Literary Miscellanea,http://oracc.museum.upenn.edu/saao/saa03,saao/saa03,Akkadian,no,no,14/05/2025
168,SAAo/SAA04: Queries to the Sungod: Divination ...,http://oracc.museum.upenn.edu/saao/saa04,saao/saa04,Akkadian,no,no,14/05/2025
169,SAAo/SAA05: The Correspondence of Sargon II Pa...,http://oracc.museum.upenn.edu/saao/saa05,saao/saa05,Akkadian,no,no,14/05/2025
170,SAAo/SAA06: Legal Transactions of the Royal Co...,http://oracc.museum.upenn.edu/saao/saa06,saao/saa06,Akkadian,no,no,14/05/2025
171,SAAo/SAA07: Imperial Administrative Records Pa...,http://oracc.museum.upenn.edu/saao/saa07,saao/saa07,Akkadian,no,no,14/05/2025
172,SAAo/SAA08: Astrological Reports to Assyrian K...,http://oracc.museum.upenn.edu/saao/saa08,saao/saa08,Akkadian,no,no,14/05/2025
173,SAAo/SAA09: Assyrian Prophecies,http://oracc.museum.upenn.edu/saao/saa09,saao/saa09,Akkadian,no,no,14/05/2025
174,SAAo/SAA10: Letters from Assyrian and Babyloni...,http://oracc.museum.upenn.edu/saao/saa10,saao/saa10,Akkadian,no,no,14/05/2025
175,SAAo/SAA11: Imperial Administrative Records Pa...,http://oracc.museum.upenn.edu/saao/saa11,saao/saa11,Akkadian,no,no,14/05/2025
176,SAAo/SAA12: Grants Decres and Gifts of the Neo...,http://oracc.museum.upenn.edu/saao/saa12,saao/saa12,Akkadian,no,no,14/05/2025
177,SAAo/SAA13: Letters from Assyrian and Babyloni...,http://oracc.museum.upenn.edu/saao/saa13,saao/saa13,Akkadian,no,no,14/05/2025
178,SAAo/SAA14: Legal Transactions of the Royal Co...,http://oracc.museum.upenn.edu/saao/saa14,saao/saa14,Akkadian,no,no,14/05/2025
179,SAAo/SAA15: The Correspondence of Sargon II Pa...,http://oracc.museum.upenn.edu/saao/saa15,saao/saa15,Akkadian,no,no,14/05/2025
180,SAAo/SAA16: The Political Correspondence of Es...,http://oracc.museum.upenn.edu/saao/saa16,saao/saa16,Akkadian,no,no,14/05/2025
181,SAAo/SAA17: The Neo-Babylonian Correspondence ...,http://oracc.museum.upenn.edu/saao/saa17,saao/saa17,Akkadian,no,no,14/05/2025
182,SAAo/SAA18: The Babylonian Correspondence of E...,http://oracc.museum.upenn.edu/saao/saa18,saao/saa18,Akkadian,no,no,14/05/2025
183,SAAo/SAA19: The Correspondence of Tiglath-Pile...,http://oracc.museum.upenn.edu/saao/saa19,saao/saa19,Akkadian,no,no,14/05/2025
184,SAAo/SAA20: Assyrian Royal Rituals and Cultic ...,http://oracc.museum.upenn.edu/saao/saa20,saao/saa20,Akkadian,no,no,14/05/2025
185,SAAo/SAA21: The Correspondence of Assurbanipal...,http://oracc.museum.upenn.edu/saao/saa21,saao/saa21,Akkadian,no,no,14/05/2025
186,SAAo/SAAS2: SAAo/Assyrian Eponym List,http://oracc.museum.upenn.edu/saao/saas2,saao/saas2,Akkadian,no,no,14/05/2025

## 2. Provenance — Tablet Find Spots

ORACC tablets come with a raw `provenience` string (e.g. `"Nineveh"`, `"Assur"`).
We pre-built a mapping from these raw strings to:
- A **normalized city name**
- A **[Pleiades](https://pleiades.stoa.org/) ID** and coordinates (lat/lon)

This was built by:
1. Collecting all unique provenience strings from ORACC + normalizing conventions to single form
2. Matching them to Pleiades gazeteer entries via API
3. Hand-verifying ambiguous cases

By default `get_provenance()` returns **only rows with a confirmed Pleiades ID**.
This is also what the pipeline uses to attach coordinates to parsed tablets.

In [20]:
# By default: only rows with a confirmed numeric Pleiades ID
prov = reference_data.get_provenance()
print(f"✅ {len(prov)} provenance mappings with confirmed Pleiades IDs")
display(prov.head(20))

✅ 263 provenance mappings with confirmed Pleiades IDs

,raw_provenience,normalized_city,pleiades_id,pleiades_title,lat,lon
0,Acharneh (Tunip),Tunip,668200,Asharne,35.2833333,36.4
1,Adab,Adab,787747618,NaN,NaN,NaN
2,Akhetaten (Mod. Amarna),el-Amarna,149576487,Amarna,27.644099597341675,30.89818203754354
3,Akhetaten (mod. el-Amarna),el-Amarna,149576487,Amarna,27.644099597341675,30.89818203754354
4,Akko,Akko,678010,Ake/Ptolemais,32.92128675,35.079835
5,Alalakh,Alalakh,309866128,Alalaḫ,36.23807544872566,36.38383192027712
6,Amarna,el-Amarna,149576487,Amarna,27.644099597341675,30.89818203754354
7,Ana,Ana,893936,Anatho,34.4678,41.9794
8,Antakya,Antakya,658381,Antiochia/Theoupolis,36.2225515,36.183214
9,Aqar Quf (Dur-Kurigalzu),Dur-Kurigalzu,893988,Dur-(Kuri)galzu,33.35607304048341,44.197416520972745
10,Arbela,Arbela,874341,Arbela/Arba-ilu,36.19131745320756,44.00938028561428
11,Arslan Tash,Arslan Tash,658399,Ballatha,36.8516655007633,38.40063987181522
12,Arslan Tash (Ḫadatu),Arslan Tash,658399,Ballatha,36.8516655007633,38.40063987181522
13,Arslantepe (Melidu),Melid,629040,Melitene,38.382217,38.361152
14,Arzawa,Arzawa,35475912,NaN,NaN,NaN
15,Ashara (Terqa),Terqa,894158,[Terqa]/Asicha?,34.9224178,40.56815636666667
16,Ashdod (Asdūdu),Ashdod,687843,Azotos Paralios,31.78042631529533,34.62164696402221
17,Ashkelon,Ashkelon,687839,Ashqelon/Ascalon,31.664797212161965,34.550521466715146
18,Ashur,Assur,893945,Ashur/‘Lamban’?/‘Liba(nai)’?,35.45557316179846,43.2613012875624
19,Assur,Assur,893945,Ashur/‘Lamban’?/‘Liba(nai)’?,35.45557316179846,43.2613012875624

In [21]:
# To see ALL mappings (including uncertain/unmatched):
from oracc_parser.utils.paths import get_provenience
prov_all = get_provenience(pleiades_only=False)
print(f"🗺️  Total provenance mappings: {len(prov_all)}")
print(f"   With Pleiades ID:           {len(prov)} ({len(prov)/len(prov_all):.0%})")
print(f"   Without Pleiades ID:        {len(prov_all) - len(prov)} (uncertain / unidentified)")

🗺️  Total provenance mappings: 333
   With Pleiades ID:           263 (79%)
   Without Pleiades ID:        70 (uncertain / unidentified)

In [8]:
# Cities with confirmed Pleiades IDs
cities = prov['normalized_city'].dropna().unique()
print(f"{len(cities)} unique cities with Pleiades coordinates:")
for c in sorted(cities)[:30]:
    print(f"  {c}")

158 unique cities with Pleiades coordinates:
  Adab
  Akko
  Alalakh
  Ana
  Antakya
  Arbela
  Arslan Tash
  Arzawa
  Ashdod
  Ashkelon
  Assur
  Babylon
  Bad-Tibira
  Balāwāt
  Bavian
  Beirut
  Beisan
  Ben Shemen
  Bisutun
  Borsippa
  Bost
  Brissa
  Burmarina
  Byblos
  Carchemish
  Cutha
  Daskyleion
  Dawali
  Der
  Dilbat

## 3. Historical Periods → Year Ranges

ORACC text metadata includes period names like `"Neo-Assyrian"`, `"Old Babylonian"`, etc.
We pre-saved a mapping from these period names to approximate year ranges.
The pipeline uses this to add `start_year` / `end_year` to every parsed tablet.

In [9]:
periods = reference_data.get_period_mapping()
print(f"{len(periods)} historical periods")
display(periods)

21 historical periods

                                   period_name  start_year  end_year
0                                  hellenistic        -323       -30
1                                   achaemenid        -550      -330
2                               Neo-Babylonian        -626      -539
3                                 Neo-Assyrian        -911      -612
4                                     Parthian        -247       224
5                            Middle Babylonian       -1595     -1155
6                              Middle Assyrian       -1363      -912
7                               Old Babylonian       -1894     -1595
8                                 Old Akkadian       -2334     -2154
9                         Early Old Babylonian       -1894     -1595
10                            First Millennium       -1000        -1
11                                    Seleucid        -312       -64
12                         Standard Babylonian       -1595     -1155
13                              Middle Hittite       -1400     -1200
14                         Neo/Late Babylonian        -626      -539
15                             Late Babylonian        -600      -501
16                                      Ur III       -2112     -2004
17                                Old Assyrian       -2025     -1750
18  Late Middle Assyrian or early Neo-Assyrian       -1200      -900
19                                     Mitanni       -1550     -1260
20                                Neo Assyrian        -911      -612

## 4. Cuneiform Sign List (8,900+ readings)

This table maps cuneiform sign names to their Unicode code points.
The parser uses it to render transliterated text as actual cuneiform characters (𒀸, 𒈾, etc.).
It was compiled from the ORACC sign list and merged with Unicode cuneiform block data.

In [10]:
signs = reference_data.get_sign_list()
print(f"{len(signs)} sign readings")
display(signs.head(20))

8901 sign readings

       ʾu₄   𒀀
0        a   𒀀
1     aia₂   𒀀
2     aya₂   𒀀
3     barₓ   𒌋
4   buniŋₓ   𒆹
5     burₓ   𒋲
6     dur₅   𒀀
7    duru₅   𒀀
8       e₄   𒀀
9       ea   𒀀
10   ebir₃   𒀀
11     emₓ   𒀀
12   epir₃   𒀀
13    eš₁₀   𒀀
14    ŋa₁₀   𒀀
15    ia₁₀   𒀀
16     id₅   𒀀
17     me₅   𒀀
18    mu₁₄   𒀀
19    sedₓ  𒈹𒁲

In [12]:
# Search for a sign reading
SIGN_QUERY = "lugal"  # Try: "an", "dingir", "sar", "gal", "ki"

mask = signs.apply(
    lambda r: SIGN_QUERY.lower() in ' '.join(r.fillna('').astype(str)).lower(),
    axis=1,
)
matches = signs[mask]
print(f"Found {len(matches)} readings for '{SIGN_QUERY}':")
display(matches)

Found 2 readings for 'dingir':

         ʾu₄  𒀀
435   dingir  𒀭
436  dingira  𒀭

## 5. POS Tags & Language Codes

**POS tags** — ORACC uses a custom tagset (e.g. `PN` = Personal Name, `GN` = Geographical Name).
We presaved a table linking each tag to its human-readable meaning.

**Language codes** — ORACC texts are tagged with BCP-47-style language codes
(e.g. `akk-x-neoass` = Neo-Assyrian Akkadian). This table documents what each code means.

In [13]:
pos = reference_data.get_pos_tags()
print(f"POS tags ({len(pos)}):")
display(pos)

POS tags (56):

,POS-tag,Meaning,Update to,To mask,Mask as
0,MN,Month Name,MN,yes,MN
1,n,Number,NUM,yes,NUM
2,u,Unknown,U,no,NaN
3,N,Noun,N,no,NaN
4,CN,Constellation Name,CN,yes,CN
5,AJ,Adjective,AJ,no,NaN
6,PRP,Preposition,PRP,no,NaN
7,V,Verb,V,no,NaN
8,IP,Independent Pronoun,IP,no,NaN
9,PN,Personal Name,PN,yes,PN
10,MOD,Modal particle,MOD,no,NaN
11,RN,Royal Name,RN,yes,PN
12,GN,Geographical Name,GN,yes,GN
13,REL,Relative Pronoun,REL,no,NaN
14,AV,Adverb,AV,no,NaN
15,SN,State Name (city name),SN,yes,GN
16,CNJ,Conjunction,CNJ,no,NaN
17,DN,Divine Name,DN,yes,DN
18,X,Broken,X,no,NaN
19,TN,Temple Name,TN,yes,GN
20,SBJ,Subjunctive,SBJ,no,NaN
21,NU,Number,NUM,yes,NUM
22,WN,Water Name,WN,yes,GN
23,EN,Ethnic Name,EN,yes,PN
24,XP,Indefinite Pronoun,XP,no,NaN
25,DP,Demonstrative Pronoun,DP,no,NaN
26,DET,Determinative Pronoun,DET,no,NaN
27,QP,Question Pronoun,QP,no,NaN
28,NINDA,typo in adsd-adart3 change to N,N,no,NaN
29,YN,typo in adsd-adart5 change to RN?,RN,yes,PN
30,ZA,typo in adsd-adart5 change to X?,X,no,NaN
31,J,Injunction?,J,no,NaN
32,PP,Possessive Pronoun,PP,no,NaN
33,RP,Reflexive Pronoun,RP,no,NaN
34,V/i,Verb (Sumerian),V,no,NaN
35,V/t,Verb (Sumerian),V,no,NaN
36,MA,Modal Adverb (Sumerian),MA,no,NaN
37,U,Unknown,U,no,NaN
38,QN,(City) Quarter Name,QN,yes,GN
39,LN,Lineage Name (ancestral name),LN,yes,PN
40,ON,Geographical Name,ON,yes,GN
41,M,Sumerian? only 15 examples mainly from CCP,NaN,no,NaN
42,S,Sumerian (only 2 examples CCP and ePSD),NaN,no,NaN
43,KN,King Name,RN,yes,RN
44,AN,Sumerian no idea,AN,no,NaN
45,O,(Sumerian) Particle,O,no,NaN
46,L,Lexical (various POS),L,no,NaN
47,Y,no idea 7 words in one lexical list dsst/Q000771,Y,no,NaN
48,PSP,(Sumerian) Postposition,PSP,no,NaN
49,FN,Sumerian no idea only in ePSD,FN,no,NaN
50,ZX,Sumerian one text in ePSD,ZX,no,NaN
51,NP,Sumerian one text in ePSD,NP,no,NaN
52,NN,Noun,N,no,NaN
53,A,Sumerian something,A,no,NaN
54,P,Sumerian something,P,no,NaN
55,Z,Sumerian something,Z,no,NaN

In [14]:
langs = reference_data.get_languages()
print(f"Language codes ({len(langs)}):")
display(langs)

Language codes (49):

,lang,language_name,Is_cuneiform,Notes,count,projects,projects_count
0,sux,Sumerian,yes,NaN,1263848,"asbp, blms, btto, cams, caspo, ccpo, cdli, cks...",26
1,akk,Akkadian,yes,NaN,1224041,"adsd, aemw, ario, asbp, btto, cams, cdli, ckst...",25
2,akk-x-neoass,Akkadian,yes,NaN,496841,"atae, cams, csik, dcclt, eisl, obmc, rinap, sa...",9
3,akk-x-stdbab,Akkadian,yes,NaN,404482,"asbp, balt, blms, cams, caspo, ccpo, cmawro, c...",21
4,akk-x-neobab,Akkadian,yes,NaN,379814,"atae, babcity, balt, borsippa, cams, csik, obm...",8
5,akk-x-midass,Akkadian,yes,NaN,167389,"aemw, akklove, balt, csik, dcclt, dsst, obmc, ...",9
6,akk-x-mbperi,Akkadian,yes,NaN,161285,"aemw, contrib, dcclt, obmc, tcma",5
7,qpc,Proto-cuneiform,no,requires different sign list and different par...,147822,"cdli, edlex",2
8,akk-x-ltebab,Akkadian,yes,NaN,130637,"cams, hbtin",2
9,akk-x-oldbab,Akkadian,yes,NaN,71438,"akklove, atae, blms, cams, caspo, cdli, csik, ...",18
10,akk-949,Akkadian,yes,NaN,54792,"btto, cmawro, dcclt, eisl, rinap",5
11,uga-040,Ugaritic,no,NaN,35221,"aemw, dcclt",2
12,sux-x-emesal,Sumerian,yes,NaN,25696,"blms, cams, ccpo, ckst, dcclt, dsst, eisl, obe...",10
13,xur,Urartian,no,NaN,22620,ecut,1
14,peo,Persian,no,NaN,7758,ario,1
15,xur-946,Urartian,no,NaN,3994,ecut,1
16,hit,Hittite,yes,NaN,1936,"aemw, contrib, dcclt",3
17,akk-x-midbab,Akkadian,yes,NaN,1828,"akklove, csik, dcclt, dccmt, obel, tcma, urap",7
18,arc,Aramaic,no,NaN,1780,"atae, balt, rinap, saao",4
19,arc-949,Aramaic,no,NaN,NaN,NaN,NaN
20,elx,Elamite,no,NaN,1383,"ario, dcclt",2
21,akk-x-stdbab-949,Akkadian,yes,NaN,1376,"csik, dcclt, eisl",3
22,akk-x-earakk,Akkadian,yes,NaN,1035,"dcclt, edlex",2
23,akk-x-oldass,Akkadian,yes,NaN,1025,"dccmt, tcma",2
24,uga,Ugaritic,yes,Ugaritic loanwords in Akkadian,724,"aemw, contrib, dcclt",3
25,xhu,Hurrian,yes,NaN,688,"aemw, dcclt",2
26,hit-946,Hittite,yes,NaN,345,"aemw, contrib, dcclt",3
27,akk-936,Akkadian,yes,NaN,270,dcclt,1
28,xur-944,Urartian,yes,NaN,202,ecut,1
29,qca,Canaanite,yes,Canaanite loanwords in Akkadian,200,"aemw, contrib",2
30,qeb,Numbers,yes,Mathematical texts,99,dccmt,1
31,akk-x-mbperi-949,Akkadian,yes,NaN,98,dcclt,1
32,akk-x-oldakk,Akkadian,yes,NaN,90,akklove,1
33,qcu,Unclear,yes,one broken text,68,cmawro,1
34,qpe,Proto-Elamite,no,NaN,56,cdli,1
35,grc,Greek,no,NaN,47,dcclt,1
36,qur,Urartian,no,NaN,40,ecut,1
37,akk-935,Akkadian,yes,NaN,32,dcclt,1
38,xhu-040,Hurrian,no,Hurrian loandwords in Ugaritic,28,aemw,1
39,akk-x-neoass-949,Akkadian,yes,NaN,27,atae,1
40,xhu-946,Hurrian,yes,Hurrian loanwords in Akkadian,23,"aemw, contrib, dcclt",3
41,sux-947,Sumerian,yes,NaN,20,dsst,1
42,egy-020,Egyptian,yes,Egyptian loandwords in Akkadian,16,"aemw, contrib",2
43,sux-x-gloss,Sumerian,yes,NaN,15,dcclt,1
44,hlu,Urartian,no,NaN,11,ecut,1
45,akk-x-neobab-949,Akkadian,yes,NaN,10,borsippa,1
46,sux-x-syll,Sumerian,yes,NaN,10,dcclt,1
47,hit-040,Hittite,no,Hittite loanwords in Ugaritic,7,aemw,1
48,akk-x-oldbab-949,Akkadian,yes,NaN,5,dcclt,1

## What's next?

- **Notebook 01 — Quickstart:** Parse a project, explore individual tablets
- **Notebook 03 — Configure & Export:** Use `RunConfig` to mask POS tags, control output format, batch-export